name: CI/CD for Flask App on Render

on:
  push:
    branches:
      - main  # Replace 'main' with your Render-tracked branch
  pull_request:
    branches:
      - main  # Optional: Run workflow for PRs targeting 'main'

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'  # Match the Python version of your app

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests (if you have a test suite)
      - name: Run tests
        run: |
          pytest tests/  # Update this path if your tests are located elsewhere
        env:
          FLASK_ENV: testing  # Set any necessary environment variables for testing

      # Step 5: Trigger Render Deployment (if manual trigger is needed)
      - name: Trigger Render Deployment
        if: success()  # Only trigger deployment if previous steps succeed
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/v1/services/<service-id>/deploys
